### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Haotian-Zhang** [mttgdd/RobotCarDataset-Scraper#7]
Hi, I wonder when I run the get_dataset.py, I got the following issue like the following,

root@de6775a680b2:/RobotCarDataset-Scraper# python3 get_datasets.py 
Traceback (most recent call last):
  File "get_datasets.py", line 15, in <module>
    from scrape_mrgdatashare import datasets_url
  File "/RobotCarDataset-Scraper/scrape_mrgdatashare.py", line 272
    print(f"Got html file as result. Wait {self.reloging_duration} seconds and re-loging...")

Could you please check it again? Thank you!

**Comment by mttgdd** [comment]
5b971d6ae5e75adf600b21cd3900be08d3a4f9d8 and d710f0d009f5d085653e086801b9521657ed2e39 fix this issue, thanks for the catch!
